document.writeln("<script>");
document.writeln("    var a_idx = 0;");
document.writeln("    jQuery(document).ready(function($) {");
document.writeln("        $(\'body\').click(function(e) {");
document.writeln("            var a = new Array(\'❤富强❤\',\'❤民主❤\',\'❤文明❤\',\'❤和谐❤\',\'❤自由❤\',\'❤平等❤\',\'❤公正❤\',\'❤法治❤\',\'❤爱国❤\',\'❤敬业❤\',\'❤诚信❤\',\'❤友善❤\');");
document.writeln("            var $i = $(\'<span></span>\').text(a[a_idx]);");
document.writeln("            a_idx = (a_idx + 1) % a.length;");
document.writeln("            var x = e.pageX,");
document.writeln("            y = e.pageY;");
document.writeln("            $i.css({");
document.writeln("                \'z-index\': 999999999999999999999999999999999999999999999999999999999999999999999,");
document.writeln("                \'top\': y - 20,");
document.writeln("                \'left\': x,");
document.writeln("                \'position\': \'absolute\',");
document.writeln("                \'font-weight\': \'bold\',");
document.writeln("                \'color\': \'rgb(\'+~~(255*Math.random())+\',\'+~~(255*Math.random())+\',\'+~~(255*Math.random())+\')\'");
document.writeln("            });");
document.writeln("            $(\'body\').append($i);");
document.writeln("            $i.animate({");
document.writeln("                \'top\': y - 180,");
document.writeln("                \'opacity\': 0");
document.writeln("            },");
document.writeln("            1500,");
document.writeln("            function() {");
document.writeln("                $i.remove();");
document.writeln("            });");
document.writeln("        });");
document.writeln("    });");
document.writeln("</script>");