document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<script src=\'https://eqcn.ajz.miesnfu.com/wp-content/plugins/wp-3d-pony/live2dw/lib/L2Dwidget.min.js\'></script>");
document.writeln("  <!--小帅哥： https://unpkg.com/live2d-widget-model-chitose@1.0.5/assets/chitose.model.json-->");
document.writeln("  <!--萌娘：https://unpkg.com/live2d-widget-model-shizuku@1.0.5/assets/shizuku.model.json-->");
document.writeln("  <!--小可爱（女）：https://unpkg.com/live2d-widget-model-koharu@1.0.5/assets/koharu.model.json-->");
document.writeln("  <!--小可爱（男）：https://unpkg.com/live2d-widget-model-haruto@1.0.5/assets/haruto.model.json-->");
document.writeln("  <!--初音：https://unpkg.com/live2d-widget-model-miku@1.0.5/assets/miku.model.json-->");
document.writeln("   <!-- 上边的不同链接显示的是不同的小人，这个可以根据需要来选择 下边的初始化部分，可以修改宽高来修改小人的大小，或者是鼠标移动到小人上的透明度，也可以修改小人在页面出现的位置。 -->");
document.writeln("    <head>");
document.writeln("        <meta charset=\'utf-8\'>");
document.writeln("    </head>");
document.writeln("    <body>");
document.writeln("        <script>");
document.writeln("        /*https://unpkg.com/live2d-widget-model-shizuku@1.0.5/assets/shizuku.model.json*/");
document.writeln("        L2Dwidget.init({ \'model\': { jsonPath:");
document.writeln("              \'https://unpkg.com/live2d-widget-model-koharu@1.0.5/assets/koharu.model.json\',");
document.writeln("            \'scale\': 1 }, \'display\': { \'position\': \'right\', \'width\': 110, \'height\': 150,");
document.writeln("            \'hOffset\': 0, \'vOffset\': -20 }, \'mobile\': { \'show\': true, \'scale\': 0.5 },");
document.writeln("          \'react\': { \'opacityDefault\': 0.8, \'opacityOnHover\': 0.1 } });");
document.writeln("      </script>");
document.writeln("    </body>");
document.writeln("</html>");
