document.writeln("	</body>");
document.writeln("	  <div >");
document.writeln("	       <canvas id=\'canvas\'></canvas>");
document.writeln("	       <canvas id=\'snow\'></canvas>");
document.writeln("	");
document.writeln("	       <div class=\'am-g\' style=\'position: fixed; bottom: 0px;\'>");
document.writeln("	           <div class=\'am-u-sm-12\'>");
document.writeln("	               <div style=\'z-index: 9999\' id=\'player\' class=\'aplayer\'>");
document.writeln("	               </div>");
document.writeln("	           </div>");
document.writeln("	       </div>");
document.writeln("	   </div>");
document.writeln("<!-- CSS代码 -->");
document.writeln("	<style type=\'text/css\'>");
document.writeln("	");
document.writeln("	 canvas {");
document.writeln("	           position: fixed;");
document.writeln("	           width: 100%;");
document.writeln("	           height: 100%;");
document.writeln("	           z-index: -1;");
document.writeln("	       }");
document.writeln("	</style>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		var canvas = document.getElementById(\'canvas\'),");
document.writeln("	    ctx = canvas.getContext(\'2d\'),");
document.writeln("	    w = canvas.width = window.innerWidth,");
document.writeln("	    h = canvas.height = window.innerHeight,");
document.writeln("	");
document.writeln("	    hue = 217,");
document.writeln("	    stars = [],");
document.writeln("	    count = 0,");
document.writeln("	    maxStars = 1300;//星星数量");
document.writeln(" ");
document.writeln("		var canvas2 = document.createElement(\'canvas\'),");
document.writeln("		ctx2 = canvas2.getContext(\'2d\');");
document.writeln("		canvas2.width = 100;");
document.writeln("		canvas2.height = 100;");
document.writeln("		");
document.writeln("		var half = canvas2.width / 2,");
document.writeln("		gradient2 = ctx2.createRadialGradient(half, half, 0, half, half, half);");
document.writeln("		gradient2.addColorStop(0.025, \'#CCC\');");
document.writeln("		gradient2.addColorStop(0.1, \'hsl(\' + hue + \', 61%, 33%)\');");
document.writeln("		gradient2.addColorStop(0.25, \'hsl(\' + hue + \', 64%, 6%)\');");
document.writeln("		gradient2.addColorStop(1, \'transparent\');");
document.writeln("		");
document.writeln("		ctx2.fillStyle = gradient2;");
document.writeln("		ctx2.beginPath();");
document.writeln("		ctx2.arc(half, half, half, 0, Math.PI * 2);");
document.writeln("		ctx2.fill();");
document.writeln("		");
document.writeln("		//End cache");
document.writeln("		");
document.writeln("		function random(min, max) {");
document.writeln("		if (arguments.length < 2) {");
document.writeln("		   max = min;");
document.writeln("		   min = 0;");
document.writeln("		}");
document.writeln("		");
document.writeln("		if (min > max) {");
document.writeln("		   var hold = max;");
document.writeln("		   max = min;");
document.writeln("		   min = hold;");
document.writeln("		}");
document.writeln("		");
document.writeln("		return Math.floor(Math.random() * (max - min + 1)) + min;");
document.writeln("		}");
document.writeln("		");
document.writeln("		function maxOrbit(x, y) {");
document.writeln("		var max = Math.max(x, y),");
document.writeln("		 diameter = Math.round(Math.sqrt(max * max + max * max));");
document.writeln("		return diameter / 2;");
document.writeln("		//星星移动范围，值越大范围越小，");
document.writeln("		}");
document.writeln("		");
document.writeln("		var Star = function () {");
document.writeln("		");
document.writeln("		this.orbitRadius = random(maxOrbit(w, h));");
document.writeln("		this.radius = random(60, this.orbitRadius) / 8;");
document.writeln("		//星星大小");
document.writeln("		this.orbitX = w / 2;");
document.writeln("		this.orbitY = h / 2;");
document.writeln("		this.timePassed = random(0, maxStars);");
document.writeln("		this.speed = random(this.orbitRadius) / 50000;");
document.writeln("		//星星移动速度");
document.writeln("		this.alpha = random(2, 10) / 10;");
document.writeln("		");
document.writeln("		count++;");
document.writeln("		stars[count] = this;");
document.writeln("		}");
document.writeln("		");
document.writeln("		Star.prototype.draw = function () {");
document.writeln("		var x = Math.sin(this.timePassed) * this.orbitRadius + this.orbitX,");
document.writeln("		 y = Math.cos(this.timePassed) * this.orbitRadius + this.orbitY,");
document.writeln("		 twinkle = random(10);");
document.writeln("		");
document.writeln("		if (twinkle === 1 && this.alpha > 0) {");
document.writeln("		   this.alpha -= 0.05;");
document.writeln("		} else if (twinkle === 2 && this.alpha < 1) {");
document.writeln("		   this.alpha += 0.05;");
document.writeln("		}");
document.writeln("		");
document.writeln("		ctx.globalAlpha = this.alpha;");
document.writeln("		ctx.drawImage(canvas2, x - this.radius / 2, y - this.radius / 2, this.radius, this.radius);");
document.writeln("		this.timePassed += this.speed;");
document.writeln("		}");
document.writeln("		");
document.writeln("		for (var i = 0; i < maxStars; i++) {");
document.writeln("		new Star();");
document.writeln("		}");
document.writeln("		");
document.writeln("		function animation() {");
document.writeln("		ctx.globalCompositeOperation = \'source-over\';");
document.writeln("		ctx.globalAlpha = 0.5; //尾巴");
document.writeln("		ctx.fillStyle = \'hsla(\' + hue + \', 64%, 6%, 2)\';");
document.writeln("		ctx.fillRect(0, 0, w, h)");
document.writeln("		");
document.writeln("		ctx.globalCompositeOperation = \'lighter\';");
document.writeln("		for (var i = 1, l = stars.length; i < l; i++) {");
document.writeln("		   stars[i].draw();");
document.writeln("		   canvas2.style.cssText = \'display:none\';");
document.writeln("		};");
document.writeln("		");
document.writeln("		window.requestAnimationFrame(animation);");
document.writeln("		}");
document.writeln("		");
document.writeln("		");
document.writeln("		animation();");
document.writeln("	</script>");
